name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - run: npm test
      - run: npm run build
      - run: ls -lh dist/recipe-search-ui-playground
#
#      - uses: guardian/actions-riff-raff@v4
#        with:
#          app: recipe-search-ui-playground
#          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
#          githubToken: ${{ secrets.GITHUB_TOKEN }}
#          contentDirectories: |
#            cdk:
#              - cdk/cdk.out
#            recipe-search-ui-playground:
#              - dist/recipe-search-ui-playground